class ProyectosPageSelectors:
    TITULO_ESPACIO_TRABAJO = "text=Mis Proyectos"
    PROYECTOS_BUTTON = 'div:nth-of-type(1)>button[aria-label="Menú Mis Proyectos"]'
    MENU_POPUP = '[aria-label="Añadir proyecto"]'#pestaña de menu popup
    TITULO_FORMULARIO = "text=Añadir proyecto" 
    CAMPO_NOMBRE = '#edit_project_modal_field_name'
    SELECT_COLOR = 'button[aria-labelledby="edit_project_modal_field_color_label"]'
    VER_COLOR = '#dropdown-select-2-option-charcoal' #color por defecto
    COLOR = 'text=Violeta'
    SUBMIT_BUTTON = 'button[type="submit"]'
    CONTENEDOR_PROYECTO = '[data-testid="task-selection-list-container"]'
    EXPLORAR_PLANTILLAS = 'a[aria-label="Explorar plantillas"]'
    PLANTILLA = 'a[data-template-name="Revisión semanal"]'
    TITULO_PLANTILLA = 'section > div > div > h1'
    COPIAR_PLANTILLA = 'button[data-template-name="Revisión semanal"]'
    ADD_FAVORITOS= 'input[name="is_favorite"]'
    PROYECTOS_FAVORITOS= 'ul[aria-label="Favoritos"] li[data-type="project_list_item"]'
    LISTA_PROYECTOS='#projects_list li[data-type="project_list_item"] a > div > span'
    NOMBRE_PROYECTO = 'text=proyecto de prueba'
    PROYECTO='#projects_list > div > div > div > div > div:nth-of-type(1)'
    PROYECTO_MENU_BUTTON = '[aria-label="Menú de opciones del proyecto"]'
    EDITAR_BUTTON = '.reactist_menulist > div:nth-of-type(1)'
    TITULO_FORM_EDITAR = 'text=Editar'
    COLOR_NUEVO = 'text=Celeste'
    PANEL = 'label[for="BOARD"]'
    ARCHIVAR_BUTTON='.reactist_menulist > div:nth-of-type(11)'
    TITULO_VENTANA_ARCHIVAR='text=¿Archivar el proyecto?'
    MSJ_CONFIRMACION_BUTTON = 'footer > div > button:nth-of-type(2)'
    ELIMINAR_BUTTON= '.reactist_menulist > div:nth-of-type(12)'
    TITULO_VENTANA_ELIMINAR='text=¿Eliminar el proyecto?'