class ProyectosPageSelectors:
    TITULO_ESPACIO_TRABAJO = "text=Mis Proyectos"
    PROYECTOS_BUTTON = 'div:nth-of-type(1)>button[aria-label="Menú Mis Proyectos"]'
    MENU_POPUP = '[aria-label="Añadir proyecto"]'#pestaña de menu popup
    TITULO_FORMULARIO = "text=Añadir proyecto" 
    CAMPO_NOMBRE = '#edit_project_modal_field_name'
    SELECT_COLOR = 'button[aria-labelledby="edit_project_modal_field_color_label"]'
    VER_COLOR = '#dropdown-select-2-option-charcoal' #color por defecto
    COLOR = 'text=Violeta'
    SUBMIT_BUTTON = 'button[type="submit"]'
    CONTENEDOR_PROYECTO = '[data-testid="task-selection-list-container"]'
    EXPLORAR_PLANTILLAS = 'a[aria-label="Explorar plantillas"]'
    SELEC_PLANTILLA = 'a[data-template-name="Revisión semanal"]'
    TITULO_PLANTILLA = 'section > div > div > h1'
    COPIAR_PLANTILLA = 'button[data-template-name="Revisión semanal"]'
    ADD_FAVORITOS= '.reactist_menulist > div:nth-of-type(2)'
    PROYECTOS_FAVORITOS= 'ul[aria-label="Favoritos"] li[data-type="project_list_item"]'
    LISTA_PROYECTOS='#projects_list li[data-type="project_list_item"] a > div > span'
    NOMBRE_PROYECTO = 'text=proyecto de prueba'
    PROYECTO='#projects_list > div > div > div > div > div:nth-of-type(1)'
    PROYECTO_MENU_BUTTON = 'button[aria-label="Menú de opciones del proyecto"]'
    EDITAR_BUTTON = '.reactist_menulist > div:nth-of-type(1)'
    TITULO_FORM_EDITAR = 'text=Editar'
    COLOR_NUEVO = 'text=Celeste'
    PANEL = 'label[for="BOARD"]'
    ARCHIVAR_BUTTON='.reactist_menulist > div:nth-of-type(11)'
    TITULO_VENTANA_ARCHIVAR='text=¿Archivar el proyecto?'
    MSJ_CONFIRMACION_BUTTON = 'footer > div > button:nth-of-type(2)'
    ELIMINAR_BUTTON= '.reactist_menulist > div:nth-of-type(12)'
    TITULO_VENTANA_ELIMINAR='text=¿Eliminar el proyecto?'
    AGREGAR_PLANTILLA_BUTTON='.reactist_menulist > a:nth-of-type(1)'
    MIS_PLANTILLAS='my-project-templates-header'
    CERRAR_BUTTON ='button[aria-label="Cerrar"]'
    AGREGAR_SECCION_BUTTON='.reactist_menulist > div:nth-of-type(4)'
    NOMBRE_SECCION='.section input'
    DESC_PLANTILLA ='[data-testid="modal-overlay"] textarea'
    PLANTILLA ='div[aria-labelledby="my-project-templates-header"] a'
    MSJ_PLANTILLA ='text=Plantilla guardada'
    TITULO_PLANTILLA='div[aria-labelledby="my-project-templates-header"] a:nth-of-type(1) h4'
    ELIMINAR_PLANTILLA_BUTTON='footer.focus-marker-enabled-within > div > div > button'
    CERRAR_VENTANA_PLANTILLA='div[data-testid="modal-overlay"] div[data-testid="button-container"] div button[aria-label="Cerrar"]'
    BOTON_COMPARTIR_PROYECTO='#share-options-button'
    CAMPO_CORREO_INVITADO='input[name="search_invitees"]'
    LISTA_CORREO_INVITADOS ='input[aria-label="Lista de colaboradores existentes"]'
    SELECT_CORREO_INVITADO='[aria-label="Lista de colaboradores existentes"]>div>div:nth-of-type(2)>div'
    AGREGAR_INVITADO_BUTTON='div.popper__overlay > div:nth-child(2)  button:nth-of-type(2)'
    TEXTO_INVITADO='text=Invitaciones enviadas'
    OVERLAY='[data-testid="popper__overlay"]'
    EXPORTAR_MENU='.reactist_menulist > div:nth-of-type(7)'
    EXPORTAR_COMO='text=Exporta como archivo CSV'
    EXPORTAR_BUTTON='div footer div button:nth-of-type(2)'