class ComentariosPageSelectors:
    PROYECTO_BUTTON = '#projects_list div[data-testid="virtuoso-item-list"]>div:nth-child(1)' #rescata el primer proyecto 
    COMENTARIO_BUTTON = 'a[data-note-type="project_note"]'
    TEXTO_COMENT_PROY = 'text=Centraliza las discusiones importantes de tu proyecto en los comentarios de proyecto.'
    CAMPO_COMENTARIO = 'p[data-placeholder="Comentar"]'
    SUBMIT_BUTTON = 'button[type="submit"]'
    COMENTARIOS_PROYECTO = '.note_content' #comentarios de proyecto
    ABRIR_TAREA = '.task_list_item >div.task_list_item__body' #seleccionar tarea de today
    ABRIR_CAMPO_COMENTARIO= 'button[data-testid="open-comment-editor-button"]'
    CERRAR_TAREA= '[aria-label="Cerrar tarea"]'
    CANCELAR_BUTTON='button[aria-label="Cerrar editor de comentarios"]'
    SELECT_COMENTARIO = '.note_text.has_avatar'
    MENU_COMENTARIO = 'button[aria-label="Opciones del comentario"]'
    ELIMINAR_COMENTARIO_BUTTON = 'div[aria-label="Opciones del comentario"] div:nth-of-type(4)'
    MENSAJE_ALERTA = 'Este comentario se eliminará permanentemente.'
    ACEPTAR_BUTTON = '.focus-marker-enabled-within footer button:nth-of-type(2)'
    EDITAR_BUTTON='[aria-label="Opciones del comentario"] div:nth-of-type(1)'
    ACTUALIZAR_BUTTON='button[data-track="comments|update_comment"]'
    CAMPO_COMENTARIO_ACTUALIZAR='div[aria-label="Comentar"]'
    SUBTAREA='.task_list_item.task_list_item--project_hidden'
    ICONO_COMENTAR_BUTTON='.task_list_item.task_list_item--project_hidden  button[aria-label="Comentar"]'
    AGREGAR_REACCION='.emojiPickerWrapper button[aria-label="Añade una reacción"]'
    EMOJIS_RECIENTES='div[data-testid="Usadas recientemente"]'
    EMOJI_VERIFICACION='div[title="botón de marca de verificación"]'
    REACCIONES_LIST='.comments_actions_line.reactions_line .reaction'
    MENU_EMOJIS='div[aria-label="Selector de emoji"]'
    CAMPO_NOTIFICAR='div[data-testid="collaboratorComboBox"] input'
    SELECT_CORREO_NOTIFICACION='div[data-testid="collaboratorComboboxPopover"]>div>div'
    CERRAR_VENTANA='button[aria-label="Close modal"]'